let bitcoinData = {
    "bpi": {
        "EUR": {
            "code": "EUR",
            "description": "Euro",
            "rate": "815.8994",
            "rate_float": 815.8994,
            "symbol": "&euro;"
        },
        "GBP": {
            "code": "GBP",
            "description": "British Pound Sterling",
            "rate": "677.4879",
            "rate_float": 677.4879,
            "symbol": "&pound;"
        },
        "USD": {
            "code": "USD",
            "description": "United States Dollar",
            "rate": "728.4816",
            "rate_float": 728.4816,
            "symbol": "&#36;"
        }
    },
    "chartName": "Bitcoin",
    "disclaimer": "This data was generated by creating random numbers and mimics the Coinbase API JSON response structure. It is NOT real data. DO NOT USE THIS TO TRADE CRYPTOCURRENCY!",
    "time": {
        "updatedISO": "2023-02-14T20:16:14.370072"
    }
}


// Can you convert $100 into Bitcoin?

let amountUSD = 100
let USDtoBitcoin = amountUSD * bitcoinData.bpi.USD.rate_float
console.log(amountUSD + " USD is equivalent to " + USDtoBitcoin + " bitcoin")

// one bitcoin to USD
let amountBitcoin = 1
let bitToUSD = amountBitcoin / bitcoinData.bpi.USD.rate_float
console.log(amountBitcoin + " bitcoin is equivalent to " + bitToUSD + " USD")


// Can you print (console.log) the currency descriptions and the rates, one per line?

for (let currency in bitcoinData.bpi) { // loop over every property in the bpi object
    let currencyData = bitcoinData.bpi[currency] // get the value for that property, an object with data about one currency
    let currencyDescription = currencyData.description // read values from this object
    let rate = currencyData.rate
    console.log(currencyDescription + " " + rate)
}